name: secure_key_manager
description: ESP32 Security Key Manager
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_classic: ^0.1.3
  permission_handler: ^11.3.0

flutter:
  uses-material-design: true
