name: secure_key_manager
description: ESP32 Security Key Manager
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
